# Generated by Django 2.2.6 on 2020-02-01 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=64)),
                ('ingredient_type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'ingredient_model',
                'verbose_name_plural': 'ingredients_model',
                'ordering': ['-ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_created=True)),
                ('ingredient_order', models.ManyToManyField(to='app.IngredientModel')),
            ],
        ),
        migrations.AddIndex(
            model_name='ingredientmodel',
            index=models.Index(fields=['ingredient_name'], name='app_ingredi_ingredi_6f6533_idx'),
        ),
    ]
